using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
namespace BootStrap_DataTable.Models
{
    public class AppContext : DbContext
    {
        public AppContext() : base("AppContext")
        {
        }
        public DbSet<Employee> Employees { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // uncomment if we don't want to pluralize the tables
            // modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            // uncomment to capture and debug sql commands generated by EF
            //System.Data.Entity.Infrastructure.Interception.DbInterception.Add(new Interceptor());

            base.OnModelCreating(modelBuilder);
        }
    }
}